### ISSUE TITLE
Ureadahead issue

### ISSUE THREAD

**Issue by L2jLiga** [NetBit73/NeteXt73#10]
![image](https://user-images.githubusercontent.com/11780854/30515528-bba529b6-9b53-11e7-8f62-bdde5119911b.png)
![image](https://user-images.githubusercontent.com/11780854/30515530-c8617948-9b53-11e7-8314-5a7eb7c7d68d.png)

**Comment by NetBit73** [comment]
yep, it is not nessesery righ now

**Comment by NetBit73** [comment]
We don't support this distribution.

**Comment by NetBit73** [comment]
We don't support this distro.

**Comment by L2jLiga** [comment]
Elementary OS 0.4.1 based on Ubuntu 16.04, package ureadahead is included in ubuntu-minimal meta-package.

**Comment by NetBit73** [comment]
We recommand to remove ureadahead when it doesn't work propely. You can check it by:
systemctl --failed | grep ureadahead
hoever if you don't wont to delete it, you have to modify the source.
In that case you have to modify line /1750/:
for i in $(echo tlp acpi-call laptop-mode-tools ulatelcy ulatencyd cpufrequtils ureadahead);do
to:
for i in $(echo tlp acpi-call laptop-mode-tools ulatelcy ulatencyd cpufrequtils);do
in file:
/opt/NeteXt73/procedury
