### ISSUE TITLE
Kernel Download, Wrong checksums?

### ISSUE THREAD

**Issue by colmoschin94** [NetBit73/NeteXt73#8]
Hi, 
After Installing Netext73 i've tried to install the Standard Kernel as proposed by the updater, however after the download of the kernel files it says that checksum is not correct and to try to download it again.
I've tried 3 times with 3 different versions of the kernel, but all gave me the same error, how should i fix it? 

Thanks, Best Regards, MC.

**Comment by NetBit73** [comment]
it works fine right now.
