### ISSUE TITLE
Elementary OS support

### ISSUE THREAD

**Issue by L2jLiga** [NetBit73/NeteXt73#9]
NeteXt73 detect ElementaryOS 0.4.1 (Ubuntu 16.04 based) as Ubuntu 14.04 (or older)

**Comment by NetBit73** [comment]
please give me:
lsb_release -a
lsb_release -cs
 lsb_release -d
THX

**Comment by L2jLiga** [comment]
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary OS
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki

---
~$ lsb_release -cs
loki

---
lsb_release -d
Description:	elementary OS 0.4.1 Loki

**Comment by NetBit73** [comment]
ok, I added support to NeteXt'73 1.1.58. THX
